Add example .env file

diff --git a/dev-scripts/download-prod-db b/dev-scripts/download-prod-db
--- a/dev-scripts/download-prod-db
+++ b/dev-scripts/download-prod-db
@@ -1,6 +1,13 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -eux
+# Exit on first failing command.
+set -e
+
+# Exit on unset variable.
+set -u
+
+# Echo commands
+set -x
 
 # Change directory to repository root.
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
@@ -17,6 +24,16 @@ set +x
 # shellcheck disable=SC1091
 . .env.prod
 set -x
+
+export LITESTREAM_REGION
+export LITESTREAM_ENDPOINT
+export LITESTREAM_ACCESS_KEY_ID
+export LITESTREAM_SECRET_ACCESS_KEY
+export LITESTREAM_BUCKET
+
+# Export DB_PATH so that litestream uses the variable to populate
+# litestream.yml.
+export DB_PATH
 
 litestream snapshots -config litestream.yml "${DB_PATH}"
 
