Simplify fixes

diff --git a/dev-scripts/run-go-tests b/dev-scripts/run-go-tests
--- a/dev-scripts/run-go-tests
+++ b/dev-scripts/run-go-tests
@@ -13,7 +13,12 @@ set -e
 # Echo commands to stdout.
 set -x
 
+# Fail when piped commands fail.
+set -o pipefail
+
 full_test=""
+# Without netgo, compilation fails under Nix.
+go_test_flags=("-tags=netgo")
 readonly COVERAGE_FILE_RAW=".coverage.out"
 readonly COVERAGE_FILE_HTML=".coverage.html"
 if [[ "$1" = "--full" ]]; then
@@ -23,11 +28,6 @@ if [[ "$1" = "--full" ]]; then
   go_test_flags+=("--coverprofile=${COVERAGE_FILE_RAW}")
 fi
 
-GO_BUILD_TAGS=("netgo")
-# Disable dynamically-loaded extensions, which cause a compile time warning.
-# https://www.arp242.net/static-go.html
-GO_BUILD_TAGS+=('sqlite_omit_load_extension')
-
 # Exit on unset variable.
 set -u
 
@@ -36,7 +36,15 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 readonly SCRIPT_DIR
 cd "${SCRIPT_DIR}/.."
 
-go test -tags "netgo sqlite_omit_load_extension" "${go_test_flags[@]}" ./...
+TEST_OUTPUT_FILE="$(mktemp)"
+readonly TEST_OUTPUT_FILE
+
+if ! go test "${go_test_flags[@]}" ./... | tee "${TEST_OUTPUT_FILE}" ; then
+  set +x
+  grep -C 3 "FAIL: " < "${TEST_OUTPUT_FILE}"
+  exit 1
+fi
+go test  "${go_test_flags[@]}" ./...
 if [[ -n "$full_test" ]]; then
   go tool cover -html "${COVERAGE_FILE_RAW}" -o "${COVERAGE_FILE_HTML}"
 fi
